#!/usr/bin/env python3

import sys
import matplotlib.pyplot as plt
import numpy as np

def plot_livetime_distribution(filename):
    """
    Plot the distribution of livetime values and calculate mean.
    
    Args:
        filename: Path to the CSV file generated by livetime_checker.sh
    """
    try:
        # Read the data
        livetimes = []
        with open(filename, 'r') as f:
            for line in f:
                line = line.strip()
                # Skip empty lines and the total line
                if not line or line.startswith('Total:'):
                    continue
                # Parse CSV: run_number,livetime
                parts = line.split(',')
                if len(parts) == 2:
                    try:
                        livetime = float(parts[1])
                        livetimes.append(livetime)
                    except ValueError:
                        continue
        
        if not livetimes:
            print(f"Error: No valid livetime data found in {filename}")
            sys.exit(1)
        
        # Calculate statistics
        mean_livetime = np.mean(livetimes)
        median_livetime = np.median(livetimes)
        std_livetime = np.std(livetimes)
        
        # Print statistics
        print(f"\n{'='*60}")
        print(f"Livetime Distribution Statistics")
        print(f"{'='*60}")
        print(f"Number of entries: {len(livetimes)}")
        print(f"Mean livetime:     {mean_livetime:.6f}")
        print(f"Median livetime:   {median_livetime:.6f}")
        print(f"Std deviation:     {std_livetime:.6f}")
        print(f"Min livetime:      {min(livetimes):.6f}")
        print(f"Max livetime:      {max(livetimes):.6f}")
        print(f"{'='*60}\n")
        
        # Create the plot
        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))
        
        # Histogram
        ax1.hist(livetimes, bins=30, edgecolor='black', alpha=0.7, color='steelblue')
        ax1.axvline(mean_livetime, color='red', linestyle='--', linewidth=2, label=f'Mean: {mean_livetime:.4f}')
        ax1.axvline(median_livetime, color='green', linestyle='--', linewidth=2, label=f'Median: {median_livetime:.4f}')
        ax1.set_xlabel('Livetime', fontsize=12)
        ax1.set_ylabel('Frequency', fontsize=12)
        ax1.set_title('Livetime Distribution (Histogram)', fontsize=14, fontweight='bold')
        ax1.legend()
        ax1.grid(alpha=0.3)
        
        # Box plot
        ax2.boxplot(livetimes, vert=True)
        ax2.set_ylabel('Livetime', fontsize=12)
        ax2.set_title('Livetime Distribution (Box Plot)', fontsize=14, fontweight='bold')
        ax2.grid(alpha=0.3, axis='y')
        
        # Save and show the plot
        plot_filename = filename.replace('.livetime', '_distribution.png')
        plt.tight_layout()
        plt.savefig(plot_filename, dpi=150)
        print(f"Plot saved to: {plot_filename}")
        plt.show()
        
    except FileNotFoundError:
        print(f"Error: File '{filename}' not found")
        sys.exit(1)
    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python3 plot_livetime.py <livetime_file>")
        print("Example: python3 plot_livetime.py MDS3a.livetime")
        sys.exit(1)
    
    plot_livetime_distribution(sys.argv[1])
